name: dynahack
base: core24
version: 'v0.6.0'
summary: DynaHack
description: |
  A NetHack variant with randomized equipment, new items, new monsters, new maps,
  new challenges and an advanced ASCII interface. https://tung.github.io/DynaHack/

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

parts:
  dynahack:
    plugin: cmake
    source: https://github.com/tung/DynaHack.git
    source-tag: "v0.6.0"
    build-packages:
      - zlib1g-dev
      - libncurses-dev
      - bison
      - flex
    stage-packages:
      - libncursesw6
    override-build: |
      craftctl default
      mv $CRAFT_PART_INSTALL/root/dynahack/dynahack-data/* $CRAFT_PART_INSTALL/
      rm -rf $CRAFT_PART_INSTALL/root

apps:
  dynahack:
    command: dynahack -H $SNAP -V $SNAP_USER_COMMON -U $SNAP_USER_COMMON
    plugs:
      - network
    environment:
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
